- src/zapv2/__init__.py
per PEP8
https://www.python.org/dev/peps/pep-0008/#module-level-dunder-names
refs: https://github.com/zaproxy/zaproxy/issues/3356
`__version__` is a convention
It could also be worth holding off until this can be automated since it adds a step to tagging a release (I asked in #python on the mozilla IRC for the best way to keep the version number in one place).
> Add __version__

- .travis.yml
- setup.py
- src/examples/basic-spider-scan.py
- src/zapv2/__init__.py
- src/zapv2/acsrf.py
- src/zapv2/ajaxSpider.py
- src/zapv2/ascan.py
- src/zapv2/authentication.py
- src/zapv2/authorization.py
- src/zapv2/autoupdate.py
- src/zapv2/brk.py
- src/zapv2/context.py
- src/zapv2/core.py
- src/zapv2/forcedUser.py
- src/zapv2/httpSessions.py
- src/zapv2/importLogFiles.py
- src/zapv2/openapi.py
- src/zapv2/params.py
- src/zapv2/pnh.py
- src/zapv2/pscan.py
- src/zapv2/script.py
- src/zapv2/search.py
- src/zapv2/selenium.py
- src/zapv2/sessionManagement.py
- src/zapv2/spider.py
- src/zapv2/stats.py
- src/zapv2/users.py
> Fix for Python 3

- src/zapv2/openapi.py
Regenerate the API of the add-on "OpenAPI Support" (upcoming version 6).
> Regenerate Openapi API

- src/zapv2/__init__.py
- src/zapv2/replacer.py
Add the API of the add-on Replacer (to be released).
> Add replacer API

- setup.py
- src/zapv2/__init__.py
Change `__init__.py` to import and add the openapi to ZAPv2 class.
Bump version of the library.
> Add openaapi to ZAPv2 class

- src/zapv2/ajaxSpider.py
- src/zapv2/reveal.py
- src/zapv2/selenium.py
Regenerate the APIs of the add-ons Ajax Spider, Reveal, and Selenium
(just doc updates).
> Regenerate add-ons' APIs

- src/zapv2/__init__.py
- tests/unit/conftest.py
- tests/unit/test_client.py
I discussed this in the google group - Zap python sdk does not validate the status code returned by Zap
> validate status code returned from Zap

- .travis.yml
Test also with Python 3.6 and 3.7 to ensure the API client still plays
nice with those versions.
Use Xenial dist which includes 3.7.
Remove 3.4, no longer supported.
> Add newer Python versions to Travis CI

- CHANGELOG.md
- src/zapv2/__init__.py
- src/zapv2/alertFilter.py
- src/zapv2/selenium.py
- src/zapv2/websocket.py
Update the APIs of the following add-ons:
- Selenium version 15.0.0;
- WebSockets version 19.
Add the API of the following add-on:
- Context Alert Filters version 8.
> Update/add APIs of add-ons

- CHANGELOG.md
- setup.py
Update changelog and descriptions for ZAP 2.8.
> Release 0.0.15

- CHANGELOG.md
- src/zapv2/__init__.py
- src/zapv2/localProxies.py
- src/zapv2/ruleConfig.py
Add core APIs to manage local proxies and rule configs, already present
in 2.8.0.
> Add more core APIs

- CHANGELOG.md
- src/examples/zap_example_api_script.py
- src/zapv2/__init__.py
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
> Fix typos in messages and examples

- CHANGELOG.md
- src/zapv2/__init__.py
- src/zapv2/graphql.py
Add the API of GraphQL add-on (version 0.2.0).
Signed-off-by: ricekot <ricekot@gmail.com>
> Add GraphQL API

- CHANGELOG.md
- setup.py
- src/zapv2/acsrf.py
- src/zapv2/ajaxSpider.py
- src/zapv2/alert.py
- src/zapv2/context.py
- src/zapv2/core.py
- src/zapv2/users.py
Regenerate core and add-ons APIs.
Update changelog and descriptions for ZAP 2.10.
> Regenerate APIs and prepare release

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- setup.py
Do not test with Python 2.7, already in end of life.
Remove Travis CI reference in README, missed in previous change.
> Remove Python 2.7

- .github/workflows/ci.yml
- CHANGELOG.md
- setup.py
- src/zapv2/__init__.py
- src/zapv2/acsrf.py
- src/zapv2/ascan.py
- src/zapv2/core.py
- src/zapv2/exim.py
- src/zapv2/network.py
- src/zapv2/pscan.py
- src/zapv2/replacer.py
- src/zapv2/selenium.py
- src/zapv2/spider.py
Update core APIs for 2.12.0.
Add the APIs of the following add-ons:
- Import/Export version 0.3.0.
Update the APIs of the following add-ons:
- Network version 0.3.0;
- Replacer version 11;
- Selenium version 15.11.0;
- Spider version 0.1.0.
Prepare release.
Remove Python 3.6 already EOL.
Test with Python 3.9.
> Add/update APIs of add-ons and core

- src/examples/zap_example_api_script.py
In order for `enable_scanners(ids)` and `disable_scanners(ids)` to work, `ids` can't be in list format.
My solution was to add the following line to the example Python script:
```py
ascanIds = ",".join(str(id) for id in ascanIds)
```
Now, instead of passing in `[1, 2, 3, 4]`, we're passing in `"1,2,3,4"`, which is able to work for the API call.
> Correctly pass scan rules' IDs in zap_example_api_script.py

- CHANGELOG.md
- src/zapv2/users.py
Return the response directly as it's not wrapped in an object.
Part of zaproxy/zaproxy#8282.
> Do not unwrap `get_user_by_id`'s response

- .github/workflows/release.yml
- RELEASING.md
Add workflow to automatically release to PyPI when the tag is pushed.
> Add workflow to release to PyPI

- .github/workflows/release.yml
Make sure to checkout the repo and install poetry before trying to build and release.
Correct syntax to only run on tag push.
> Fix issues in release workflow

- CONTRIBUTING.md
- README.md
- pyproject.toml
- src/zapv2/__init__.py
Move contributing guidelines to its own file to have the README just for usage information and be more suitable as long description of the project (show in PyPI website).
Also, include Custom Payloads in the API client, missed in previous change.
---
Release failed because of missing long desc:
> ERROR `long_description` has syntax errors in markup and would not be rendered on PyPI.
> No content rendered from RST source. 
https://github.com/zaproxy/zap-api-python/actions/runs/9021271433/job/24788221368#step:6:20
> Restructure docs to use README as long desc

- CHANGELOG.md
- pyproject.toml
- src/zapv2/__init__.py
- src/zapv2/automation.py
Return the response directly as it's not wrapped in an object.
Prepare release.
---
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/SXvHcCSADPc/m/ZTDibyhrBAAJ
> Do not unwrap `plan_progress`'s response

- CHANGELOG.md
- pyproject.toml
- src/zapv2/__init__.py
> Prepare next dev iteration
