zaproxy/zap-api-python

setup.py
src/examples/zap-baseline.py
src/zapv2/ajaxSpider.py
src/zapv2/core.py
src/zapv2/httpSessions.py
src/zapv2/selenium.py
src/zapv2/spider.py

Plan is to publish 'dev' releases just on github rather than on pypi.
Then install via URL for the weekly docker image.

Updated for latest API changes and baseline

---

.travis.yml
pylama.ini
setup.py
src/examples/zap-baseline.py
src/zapv2/__init__.py
tests/unit/conftest.py
tests/unit/test_client.py

hi @psiinon and @thc202,
I'm sorry it took so long, I was a little overloaded with other projects :-(
I added support for:
* travis-ci.org - builds successfully here: https://travis-ci.org/jotes/zap-api-python/builds/196926686
* pylama - It's like a unified command for various python linters. I currently decided to enable only pyflakes to avoid too many warnings and errors.
* I removed some of methods/properties/variables that weren't required/used in the project (feel free to lecture me If I removed something necessary :D).
I decided to add 3 small unit-tests because a lot of code is basically a wrapper for ZAProxy API, so I think that integration tests could be more valuable. If you think that's not enough -> I can add more of them.
Could you review? Thanks in advance!

added travis and linter.

---

README.md
src/examples/basic-spider-scan.py

Will replace https://github.com/zaproxy/zaproxy/wiki/ApiPython page with
a link to this page.

Added simple example and changed wiki link

---

setup.py
src/zapv2/__init__.py
src/zapv2/importurls.py

Add the API of the add-on "Import files containing URLs" (version 3).
Bump version of the library.

Add importurls API

---

README.md

Add and update the release steps in README file:
- Tag (and push) the new version;
- Build source and wheel;
- Sign the distribution files;
- Upload with twine (more secure).

Update release steps in README file

---

setup.py
src/zapv2/__init__.py

Update descriptions to mention ZAP 2.7.
Bump version.

Update descriptions for ZAP 2.7.0

---

src/zapv2/__init__.py
src/zapv2/websocket.py

Add the API of WebSockets add-on (version 15).

Add websocket API

---

src/zapv2/__init__.py

An exception is being raised immediately before that.
Issue reported by `lgtm.com`.

Remove unnecessary return statement

---

doc/conf.py

Comment out unused imports in doc/conf.py.

Address unused import warnings

---

CHANGELOG.md
src/zapv2/__init__.py
src/zapv2/soap.py

Add the API of SOAP Scanner add-on (version 3).

Add soap API

---

CHANGELOG.md
src/zapv2/importurls.py
src/zapv2/replacer.py

Update Replacer API, per release of version 7.
Add description to Importurls API endpoint.

Update Replacer and Importurls

---

setup.py
tests/unit/test_client.py

Cope with other entries in proxies, assert just that http and https have
the expected values.

Fix tests in Travis CI

---

CHANGELOG.md
setup.py
src/zapv2/__init__.py

Prepare next dev iteration

---

CHANGELOG.md
src/zapv2/__init__.py
src/zapv2/accessControl.py
src/zapv2/alert.py
src/zapv2/alertFilter.py
src/zapv2/autoupdate.py
src/zapv2/brk.py
src/zapv2/core.py
src/zapv2/exportreport.py
src/zapv2/pscan.py
src/zapv2/replacer.py
src/zapv2/revisit.py
src/zapv2/script.py
src/zapv2/wappalyzer.py

Regenerate core and add-ons APIs.

Regenerate APIs

---

src/examples/README.md

I use the specific commit, just in case it changes name again.

Correct link to Docker script

---

.gitignore

Ignore Eclipse files

---

CHANGELOG.md
src/zapv2/graphql.py

- Add new API actions and views. See 
zaproxy/zap-extensions#2573.
Signed-off-by: ricekot <ricekot@gmail.com>

Update GraphQL API

---

src/examples/README.md

Link to the site for info about the baseline scan.
Update link to zaproxy repo, use main branch.

Update examples' README

---

RELEASING.md

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

Tweak release instructions

---

.github/workflows/ci.yml
README.md

Use `main` for the default branch.

Update default branch name

---

CHANGELOG.md
setup.py
src/zapv2/__init__.py

Correct the module version and download link.

Release 0.1.1

---

tests/unit/conftest.py

Replace `@pytest.yield_fixture` with `@pytest.fixture`.

Address test deprecations

---

CHANGELOG.md
src/zapv2/__init__.py

Change the request functions to allow to specify the method and body.

Allow to call the API with HTTP method and body

---

.github/workflows/ci.yml
CHANGELOG.md
src/zapv2/alert.py
src/zapv2/core.py
src/zapv2/selenium.py

Update core APIs for 2.14.0.
Update the APIs of the following add-on:
- Selenium version 15.15.0.
Prepare release.
Test with newer Python version.

Update APIs of add-ons and core

---

setup.py

Update ZAP version for package desc

---

.github/workflows/ci.yml

Update `actions/setup-python` to latest version.

Update GitHub Action in CI workflow
